name: GHCR Delete Image

description: >
  Delete GitHub Container Registry Image by specified tag (or without tag).
  Options tag, untagged-keep-latest and untagged-older-than mutually exclusive.

author: bots-house

branding:
  icon: delete
  color: blue

inputs:
  owner:
    description: >
      Owner of the package (user or organization)
    required: true

  name:
    description: >
      Name of the package containing the version to delete.
    required: true

  token:
    description: >
      Token with the necessary scopes to delete package versions.
    required: true

  tag:
    description: >
      Tag to delete
    required: false

  untagged-keep-latest:
    description: >
      Delete all untagged images except the last N
    required: false

  untagged-older-than:
    description: >
      Delete all untagged images older than N in days.
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
