name: "CI"

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test-code:
    name: Test Code
    env:
      INTEGRATION_TEST_TOKEN: ${{ secrets.GCR_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  test-actions:
    name: Test Action
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_TOKEN }}

      - name: Build and Push Dummy Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.dummy
          tags: |
            ghcr.io/${{ github.repository_owner }}/ghcr-delete-image-dummy:${{ github.run_number }}

      - uses: ./
        with:
          owner: bots-house
          name: ghcr-delete-image-dummy
          token: ${{ secrets.GCR_TOKEN }}
          tag: ${{ github.run_number }}
