name: "CI"

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  tests:
    name: Unit & Integration Tests
    env:
      INTEGRATION_TEST_TOKEN: ${{ secrets.GCR_TOKEN }} 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: ./
  #     with:
  #       milliseconds: 1000
